backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

publish_mode: editorial_workflow

# To use the local backend, uncomment the following line
local_backend: true

slug:
  encoding: ascii
  clean_accents: true


patterns:
  pattern_url: &pattern_url
    - "^https?:\/\/.+"
    - "url is not valid"

collections:
  - name: "organizations"
    label: "Organizations"
    folder: "content/organizations"
    identifier_field: title
    slug: "{{slug}}"
    path: "{{slug}}/_index"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string", required: true}
      - {
          label: "Website", 
          name: "website", 
          widget: "string", 
          required: false, 
          pattern: *pattern_url,
        }
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    identifier_field: title
    slug: "{{slug}}"
    path: "{{slug}}/_index"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string", required: true}
      - {label: "Parent Category", name: "parent", widget: "relation", collection: "categories", search_fields: ["title"], value_field: "title", required: false}
  - name: "resources"
    label: "Ressources"
    folder: "content/resources"
    create: true
    slug: "{{fields.publication_date}}-{{fields.title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publication date", name: "publication_date", widget: "datetime", format: "YYYY-MM-DD", time_format: false, required: true}
      - label: "Authors"
        name: "authors"
        widget: "list"
        required: true
        fields:
          - {label: "Name", name: "title", widget: "string"}
          - {
              label: "Organization", 
              name: "organization", 
              widget: "relation",
              collection: "organizations",
              search_fields: ["title"],
              value_field: "{{slug}}",
              display_fields: ["title"],
              required: false
            }
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: true
      - {label: "Tags - separate by a comma ,", name: "tags", widget: "list", required: false}
      - {
          label: "Resource type", 
          name: "resource_type", 
          widget: "select", 
          options: ["research_paper", "study", "guide", "tool", "presentation"], 
          required: false
        }
      - {label: "Summary", name: "summary", widget: "markdown", required: true}
      - {label: "Content", name: "content", widget: "markdown", required: false}
      - {label: "Source URL", name: "source_url", widget: "string", pattern: *pattern_url, required: true}
      - {label: "Source Document", name: "source_document", widget: "string", pattern: *pattern_url, required: false}
      - label: "Source Organizations"
        name: "source_organizations"
        widget: "relation"
        collection: "organizations"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false
      - label: "Langue"
        name: "language"
        widget: "select"
        options: ["fr", "en", "es", "de"]